# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{stella}
  s.version = "2.1.2.004"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Delano Mandelbaum"]
  s.date = %q{2011-07-08}
  s.default_executable = %q{stella}
  s.description = %q{Define realistic testplans and run them against your webapps}
  s.email = %q{delano@solutious.com}
  s.executables = ["stella"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
     "README.md",
     "TODO"
  ]
  s.files = [
    ".gitignore",
     ".gitmodules",
     "CHANGES.txt",
     "Gemfile",
     "LICENSE.txt",
     "README.md",
     "Rakefile",
     "Rudyfile",
     "TODO",
     "VERSION.yml",
     "bin/stella",
     "certs/README.txt",
     "certs/cacerts.pem",
     "certs/gd-class2-root.crt",
     "certs/gd_bundle.crt",
     "certs/gd_intermediate.crt",
     "certs/startssl-ca.pem",
     "certs/startssl-sub.class1.server.ca.pem",
     "certs/stella-master.crt",
     "lib/stella.rb",
     "lib/stella/cli.rb",
     "lib/stella/client.rb",
     "lib/stella/core_ext.rb",
     "lib/stella/engine.rb",
     "lib/stella/report.rb",
     "lib/stella/testplan.rb",
     "lib/stella/utils.rb",
     "stella.gemspec",
     "support/sample_webapp/app.rb",
     "support/sample_webapp/config.ru",
     "support/useragents.txt",
     "try/00_basics_try.rb",
     "try/01_selectable_try.rb",
     "try/09_utils_try.rb",
     "try/10_stella_object_try.rb",
     "try/40_report_try.rb",
     "try/90_class_syntax_try.rb",
     "try/emhttp.rb",
     "try/rubyroute.rb",
     "try/support/file.bmp",
     "try/support/file.gif",
     "try/support/file.ico",
     "try/support/file.jpeg",
     "try/support/file.jpg",
     "try/support/file.png",
     "try/traceviz.rb",
     "vendor/httpclient-2.1.5.2/httpclient.rb",
     "vendor/httpclient-2.1.5.2/httpclient/auth.rb",
     "vendor/httpclient-2.1.5.2/httpclient/cacert.p7s",
     "vendor/httpclient-2.1.5.2/httpclient/cacert_sha1.p7s",
     "vendor/httpclient-2.1.5.2/httpclient/connection.rb",
     "vendor/httpclient-2.1.5.2/httpclient/cookie.rb",
     "vendor/httpclient-2.1.5.2/httpclient/http.rb",
     "vendor/httpclient-2.1.5.2/httpclient/session.rb",
     "vendor/httpclient-2.1.5.2/httpclient/ssl_config.rb",
     "vendor/httpclient-2.1.5.2/httpclient/timeout.rb",
     "vendor/httpclient-2.1.5.2/httpclient/util.rb"
  ]
  s.homepage = %q{http://github.com/solutious/stella}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{stella}
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Define realistic testplans and run them against your webapps}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<familia>, [">= 0.7.1"])
      s.add_runtime_dependency(%q<gibbler>, [">= 0.8.9"])
      s.add_runtime_dependency(%q<drydock>, [">= 0.6.9"])
      s.add_runtime_dependency(%q<benelux>, [">= 0.6.1"])
      s.add_runtime_dependency(%q<sysinfo>, [">= 0.7.3"])
      s.add_runtime_dependency(%q<storable>, [">= 0.8.8"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.4.4"])
      s.add_runtime_dependency(%q<public_suffix_service>, [">= 0.8.1"])
      s.add_runtime_dependency(%q<whois>, [">= 1.6.6"])
      s.add_runtime_dependency(%q<yajl-ruby>, [">= 0.7.9"])
    else
      s.add_dependency(%q<familia>, [">= 0.7.1"])
      s.add_dependency(%q<gibbler>, [">= 0.8.9"])
      s.add_dependency(%q<drydock>, [">= 0.6.9"])
      s.add_dependency(%q<benelux>, [">= 0.6.1"])
      s.add_dependency(%q<sysinfo>, [">= 0.7.3"])
      s.add_dependency(%q<storable>, [">= 0.8.8"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.4"])
      s.add_dependency(%q<public_suffix_service>, [">= 0.8.1"])
      s.add_dependency(%q<whois>, [">= 1.6.6"])
      s.add_dependency(%q<yajl-ruby>, [">= 0.7.9"])
    end
  else
    s.add_dependency(%q<familia>, [">= 0.7.1"])
    s.add_dependency(%q<gibbler>, [">= 0.8.9"])
    s.add_dependency(%q<drydock>, [">= 0.6.9"])
    s.add_dependency(%q<benelux>, [">= 0.6.1"])
    s.add_dependency(%q<sysinfo>, [">= 0.7.3"])
    s.add_dependency(%q<storable>, [">= 0.8.8"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.4"])
    s.add_dependency(%q<public_suffix_service>, [">= 0.8.1"])
    s.add_dependency(%q<whois>, [">= 1.6.6"])
    s.add_dependency(%q<yajl-ruby>, [">= 0.7.9"])
  end
end

